project: dnn-lab5
usecase: usecase-2
arch: lstm

config:
  max_len: 500
  max_words: 5000
  embedding_dim: 64
  lstm_units: 128
  batch_size: 128
  epochs: 10
  optimizer: adam
  loss: binary_crossentropy