project: dnn_lab5

config:
  max_len: 500
  max_words: 5000
  embedding_dim: 32
  lstm_units: 100
  dropout_rate: 0.2
  recurrent_dropout: 0.2
  batch_size: 64
  epochs: 10
  optimizer: adam
  loss: binary_crossentropy